# Generated by Django 3.1.7 on 2021-04-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('investment_value', models.DecimalField(decimal_places=2, max_digits=1000000000)),
                ('sector', models.CharField(max_length=30)),
                ('risk_profile', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=5)),
                ('graph_type', models.CharField(max_length=10)),
            ],
        ),
    ]
