# Generated by Django 3.1.7 on 2021-05-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='investment_value',
            field=models.PositiveIntegerField(),
        ),
    ]
