# Generated by Django 3.1.7 on 2021-05-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210501_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='investment_value',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000),
        ),
    ]
